# Generated by Django 2.1.2 on 2018-12-06 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=128)),
                ('tool', models.CharField(max_length=128)),
                ('num', models.IntegerField(default=0)),
                ('skill', models.CharField(max_length=128)),
                ('count', models.IntegerField(default=0)),
                ('publishing', models.BooleanField(default=True)),
            ],
        ),
    ]
